language: cpp
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y python-serial srecord
install:
- wget https://github.com/GeorgeHahn/nodemcu-firmware/raw/travis/tools/esp-open-sdk.tar.gz -O tools/esp-open-sdk.tar.gz
- tar -zxvf tools/esp-open-sdk.tar.gz
- export PATH=$PATH:$PWD/esp-open-sdk/sdk:$PWD/esp-open-sdk/xtensa-lx106-elf/bin
- wget http://bbs.espressif.com/download/file.php?id=1613 -O tools/ESP8266_NONOS_SDK_V2.0.0_16_07_19.zip
- unzip tools/ESP8266_NONOS_SDK_V2.0.0_16_07_19.zip
- mv tools/ESP8266_NONOS_SDK_V2.0.0_16_07_19/ESP8266_NONOS_SDK tools/ESP8266_NONOS_SDK
script:
- make all SDK_BASE="$PWD/ESP8266_NONOS_SDK"
- cd firmware/
- ls
- file_name="esp_mqtt_v${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER}.bin"
- srec_cat -output ${file_name} -binary 0x00000.bin -binary -fill 0xff 0x00000 0x40000 0x40000.bin -binary -offset 0x40000
deploy:
provider: releases
api_key:
file: "$TRAVIS_BUILD_DIR/firmware/${file_name}"
skip_cleanup: true
on:
tags: true
repo: tuanpmt/esp_mqtt
